#ifndef __H_KEYBOARD__
#define __H_KEYBOARD__

#define KEY_GRP_ESC    (0)
#define KEY_GRP_CR     (3)
#define KEY_GRP_SPACE  (6)
#define KEY_GRP_LEFT   (7)
#define KEY_GRP_UP     (7)
#define KEY_GRP_RIGHT  (7)
#define KEY_GRP_DOWN   (7)
#define KEY_GRP_ENTER  (9)
#define KEY_GRP_YEN    (1)
#define KEY_GRP_BS     (1)
#define KEY_GRP_COMMA  (6)
#define KEY_GRP_PERIOD (6)
#define KEY_GRP_C      (5)
#define KEY_GRP_D      (4)
#define KEY_GRP_E      (2)
#define KEY_GRP_F      (4)
#define KEY_GRP_H      (4)
#define KEY_GRP_P      (3)
#define KEY_GRP_Q      (2)
#define KEY_GRP_S      (3)
#define KEY_GRP_V      (5)
#define KEY_GRP_X      (5)

#define KEY_BIT_ESC    (1)
#define KEY_BIT_CR     (5)
#define KEY_BIT_SPACE  (5)
#define KEY_BIT_LEFT   (3)
#define KEY_BIT_UP     (4)
#define KEY_BIT_RIGHT  (5)
#define KEY_BIT_DOWN   (6)
#define KEY_BIT_ENTER  (6)
#define KEY_BIT_YEN    (6)
#define KEY_BIT_BS     (7)
#define KEY_BIT_COMMA  (1)
#define KEY_BIT_PERIOD (2)
#define KEY_BIT_C      (4)
#define KEY_BIT_D      (0)
#define KEY_BIT_E      (3)
#define KEY_BIT_F      (1)
#define KEY_BIT_H      (3)
#define KEY_BIT_P      (2)
#define KEY_BIT_Q      (1)
#define KEY_BIT_S      (7)
#define KEY_BIT_V      (5)
#define KEY_BIT_X      (3)

#define KEY_SCAN_CODE_ESC     ( KEY_GRP_ESC    * 8 + KEY_BIT_ESC    )
#define KEY_SCAN_CODE_CR      ( KEY_GRP_CR     * 8 + KEY_BIT_CR     )
#define KEY_SCAN_CODE_SPACE   ( KEY_GRP_SPACE  * 8 + KEY_BIT_SPACE  )
#define KEY_SCAN_CODE_LEFT    ( KEY_GRP_LEFT   * 8 + KEY_BIT_LEFT   )
#define KEY_SCAN_CODE_UP      ( KEY_GRP_UP     * 8 + KEY_BIT_UP     )
#define KEY_SCAN_CODE_RIGHT   ( KEY_GRP_RIGHT  * 8 + KEY_BIT_RIGHT  )
#define KEY_SCAN_CODE_DOWN    ( KEY_GRP_DOWN   * 8 + KEY_BIT_DOWN   )
#define KEY_SCAN_CODE_ENTER   ( KEY_GRP_ENTER  * 8 + KEY_BIT_ENTER  )
#define KEY_SCAN_CODE_YEN     ( KEY_GRP_YEN    * 8 + KEY_BIT_YEN    )
#define KEY_SCAN_CODE_BS      ( KEY_GRP_BS     * 8 + KEY_BIT_BS     )
#define KEY_SCAN_CODE_COMMA   ( KEY_GRP_COMMA  * 8 + KEY_BIT_COMMA  )
#define KEY_SCAN_CODE_PERIOD  ( KEY_GRP_PERIOD * 8 + KEY_BIT_PERIOD )
#define KEY_SCAN_CODE_C       ( KEY_GRP_C      * 8 + KEY_BIT_C      )
#define KEY_SCAN_CODE_D       ( KEY_GRP_D      * 8 + KEY_BIT_D      )
#define KEY_SCAN_CODE_E       ( KEY_GRP_E      * 8 + KEY_BIT_E      )
#define KEY_SCAN_CODE_F       ( KEY_GRP_F      * 8 + KEY_BIT_F      )
#define KEY_SCAN_CODE_H       ( KEY_GRP_H      * 8 + KEY_BIT_H      )
#define KEY_SCAN_CODE_P       ( KEY_GRP_P      * 8 + KEY_BIT_P      )
#define KEY_SCAN_CODE_Q       ( KEY_GRP_Q      * 8 + KEY_BIT_Q      )
#define KEY_SCAN_CODE_S       ( KEY_GRP_S      * 8 + KEY_BIT_S      )
#define KEY_SCAN_CODE_V       ( KEY_GRP_V      * 8 + KEY_BIT_V      )
#define KEY_SCAN_CODE_X       ( KEY_GRP_X      * 8 + KEY_BIT_E      )

#define KEY_SNS_ESC     (1 << KEY_BIT_ESC    )
#define KEY_SNS_CR      (1 << KEY_BIT_CR     )
#define KEY_SNS_SPACE   (1 << KEY_BIT_SPACE  )
#define KEY_SNS_LEFT    (1 << KEY_BIT_LEFT   )
#define KEY_SNS_UP      (1 << KEY_BIT_UP     )
#define KEY_SNS_RIGHT   (1 << KEY_BIT_RIGHT  )
#define KEY_SNS_DOWN    (1 << KEY_BIT_DOWN   )
#define KEY_SNS_ENTER   (1 << KEY_BIT_ENTER  )
#define KEY_SNS_YEN     (1 << KEY_BIT_YEN    )
#define KEY_SNS_COMMA   (1 << KEY_BIT_COMMA  )
#define KEY_SNS_PERIOD  (1 << KEY_BIT_PERIOD )
#define KEY_SNS_C       (1 << KEY_BIT_C      )
#define KEY_SNS_D       (1 << KEY_BIT_D      )
#define KEY_SNS_E       (1 << KEY_BIT_E      )
#define KEY_SNS_F       (1 << KEY_BIT_F      )
#define KEY_SNS_H       (1 << KEY_BIT_H      )
#define KEY_SNS_P       (1 << KEY_BIT_P      )
#define KEY_SNS_Q       (1 << KEY_BIT_Q      )
#define KEY_SNS_S       (1 << KEY_BIT_S      )
#define KEY_SNS_V       (1 << KEY_BIT_V      )
#define KEY_SNS_X       (1 << KEY_BIT_X      )

#endif